kind = "mobile"
previewPath = "/mobile/"
title = "CampusFound Mobile"
version = "1.0.0"
id = "artifacts/campus-found-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24563

[services.development]
run = "pnpm --filter @workspace/campus-found-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/campus-found-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/campus-found-mobile", "run", "serve" ]

[services.env]
PORT = "24563"
BASE_PATH = "/mobile/"
